<?php

namespace frontend\controllers;

use common\helpers\TimeHelper;
use common\models\ArticleCategory;
use Yii;
use yii\web\Controller;


/**
 * FrontendController
 * @author Dung Phan Xuan <dungphanxuan999@gmail.com>
 */
abstract class FrontendController extends Controller
{
    /**
     * @var string the title to display in the headline bar under that navigation. e.g. 'Yii Framework Wiki'
     */
    public $sectionTitle;

    /**
     * @var string part of the title to add in the HTML page title. e.g. 'Wiki'
     * Defaults to [[sectionTitle]], if not explicitly set.
     */
    public $headTitle;

    public $enableCsrfValidation = false;

    public $site_id;

    public $category_id;

    /*
     * Seo Index Flag
     * */
    public $is_index = false;


    /*  public function behaviors()
      {
          return ArrayHelper::merge(parent::behaviors(), [
              [
                  'class' => ActionTimeFilter::class,
                  'type'  => 2
              ],
          ]);
      }*/

    public function init()
    {
        //Yii::$app->language = 'vi';
        header('Access-Control-Allow-Origin: *');
        //todo log request

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            /*Todo clear cache*/
            $cacheKey = CACHE_SYSTEM_COMMON;
            $data = systemCache()->get($cacheKey);

            /*Clear cache taget 1 day request*/
            //if (true) {
            if ($data === false) {
                \Yii::$app->cache->flush();
                \Yii::$app->dcache->flush();
                \Yii::$app->scache->flush();

                //Clear Assets Folder
                $dirAdsAssets = Yii::getAlias('@base') . '/assets';
                rrmdir($dirAdsAssets);

                //Clear Storage File Cache
                $dirFileCache = Yii::getAlias('@storage') . '/cache';
                rrmdir($dirFileCache, 2);

                $this->updateData();

                systemCache()->set($cacheKey, 1, TimeHelper::SECONDS_IN_A_DAY);
            }
            //Default router

            //dd(Yii::$app->getUrlManager()->rules);

            return true;
        }

        return false;
    }

    protected function updateData()
    {
        //Update Article Category count
        ArticleCategory::updateTotal();
    }

}
