<option value="0">Chọn Dự án</option>
<option value="285">KHU ĐÔ THỊ MỚI VĂN PHÚ HÀ ĐÔNG</option>
<option value="279">TỔ HỢP THƯƠNG MẠI DỊCH VỤ VÀ CĂN HỘ ROMAN PLAZA</option>
<option value="280">TỔ HỢP TÒA NHÀ THE PRIDE</option>
<option value="291">CHUNG CƯ CT4 VIMECO</option>
<option value="281">TÒA NHÀ HỖN HỢP ĐẠI ĐÔNG Á</option>
<option value="282">CT1 TRUNG VĂN - VINACONEX 3</option>
<option value="286">N04B NGOẠI GIAO ĐOÀN</option>
<option value="295">KHU NHÀ PHỐ THƯƠNG MẠI GELEXIMCO LÊ TRỌNG TẤN, HÀ ĐÔNG</option>
<option value="269">KHU NHÀ PHỐ THƯƠNG MẠI 24H VẠN PHÚC, HÀ ĐÔNG</option>
<option value="278">NHÀ Ở XÃ HỘI THE VESTA</option>
<option value="287">TÂY HỒ RIVER VIEW</option>
<option value="290">THE LINK 345-CT1</option>
<option value="289">HÀ NỘI GARDEN VILLA (HÀ NỘI GARDEN CITY)</option>
<option value="413">VIWASEEN TOWER</option>
<option value="292">CHUNG CƯ DREAM CENTER HOME 282 NGUYỄN HUY TƯỞNG</option>
<option value="296">BIỆT THỰ NHÀ VƯỜN THE PHOENIX GARDEN</option>
<option value="297">ROMANTIC PARK TÂY HỒ TÂY</option>
<option value="298">SUN GRAND CITY QUẢNG AN RESIDENCE</option>
<option value="299">KHU BIỆT THỰ SINH THÁI CẨM ĐÌNH</option>
<option value="300">HỒNG HÀ TOWER</option>
<option value="301">IA20 CIPUTRA</option>
<option value="302">AN BÌNH BUILDING</option>
<option value="303">GREEN PARK CT15 VIỆT HƯNG</option>
<option value="304">NHÀ Ở CHO CÁN BỘ CHIẾN SỸ BỘ CÔNG AN</option>
<option value="307">HATECO XUÂN PHƯƠNG</option>
<option value="305">SMILE BUILDING</option>
<option value="306">VINCITY GIA LÂM</option>
<option value="308">VINCITY ĐAN PHƯỢNG</option>
<option value="309">THE ZEN RESIDENCE</option>
<option value="310">EMERALD CENTER PARK</option>
<option value="311">IMPERIA SKY GARDEN</option>
<option value="312">ECO LAKE VIEW</option>
<option value="313">ONE 18 NGỌC LÂM</option>
<option value="314">MIPEC HIGHRISE</option>
<option value="315">HUD3 NGUYỄN ĐỨC CẢNH</option>
<option value="342">MB GRAND TOWER</option>
<option value="316">STELLAR PALACE</option>
<option value="317">CHUNG CƯ 199 HỒ TÙNG MẬU</option>
<option value="318">KOSMO TÂY HỒ</option>
<option value="319">HOUSINCO GRAND TOWER</option>
<option value="320">MỸ ĐÌNH PLAZA 2</option>
<option value="321">ECOHOME PHÚC LỢI</option>
<option value="322">ECO GREEN TOWER</option>
<option value="323">ĐỒNG PHÁT RESIDENT</option>
<option value="324">D' EL DORADO</option>
<option value="325">CHUNG CƯ 536A MINH KHAI</option>
<option value="326">CHUNG CƯ A10-A14 NAM TRUNG YÊN</option>
<option value="332">SUNSHINE RIVERSIDE</option>
<option value="333">OSAKA COMPLEX</option>
<option value="331">SUNSHINE CENTER</option>
<option value="327">LEGEND PARK</option>
<option value="328">HOÀNG CẦU SKYLINE</option>
<option value="329">ANLAND NAM CƯỜNG</option>
<option value="330">SUNSHINE GARDEN</option>
<option value="334">CHUNG CƯ C1 C2 XUÂN ĐỈNH</option>
<option value="335">CT2B NGHĨA ĐÔ</option>
<option value="336">HÀ NỘI AQUA CENTRAL</option>
<option value="337">RIVERSIDE GARDEN</option>
<option value="338">ECO CITY VIỆT HƯNG</option>
<option value="339">ORIENTAL PLAZA</option>
<option value="340">BRG PARK RESIDENCE</option>
<option value="341">T&amp;T RIVERVIEW</option>
<option value="343">CHUNG CƯ 31 LÁNG HẠ</option>
<option value="344">B1-B2 TÂY NAM LINH ĐÀM</option>
<option value="345">XUÂN MAI SPARKS TOWER</option>
<option value="346">HẢI ĐĂNG TOWER</option>
<option value="347">AN BÌNH CITY</option>
<option value="348">CHUNG CƯ ĐẠI THANH</option>
<option value="349">HPC LANDMARK 105</option>
<option value="350">CENTRAL FIELD TRUNG KÍNH</option>
<option value="351">PARK VIEW CITY</option>
<option value="352">THE TWO RESIDENCE - GAMUDA GARDEN</option>
<option value="353">LAKESIDE RESIDENCES - GOLDMARK CITY</option>
<option value="354">SUN GRAND CITY</option>
<option value="355">PARK 12 PARK HILL - TIMES CITY</option>
<option value="356">THE GOLDEN PALM LÊ VĂN LƯƠNG</option>
<option value="357">MANDARIN GARDEN 2</option>
<option value="358">FLC STAR TOWER</option>
<option value="359">TÒA NHÀ VĂN PHÒNG EUROWINDOW</option>
<option value="360">ORIENTAL TOWER</option>
<option value="361">PV OIL TOWER</option>
<option value="362">GIẢNG VÕ LAKE VIEW BUILDING</option>
<option value="363">OCEAN PARK</option>
<option value="364">VINCOM CENTER PHẠM NGỌC THẠCH</option>
<option value="365">LEPARC BY GAMUDA</option>
<option value="366">AEON MALL LONG BIÊN</option>
<option value="367">VINCOM CENTER LONG BIÊN</option>
<option value="368">SAVICO MEGAMALL LONG BIÊN</option>
<option value="369">HDB PLAZA</option>
<option value="370">RIVERA PARK HÀ NỘI</option>
<option value="371">LOUIS CITY</option>
<option value="372">EUROWINDOW RIVER PARK</option>
<option value="373">VINHOMES THE HARMONY</option>
<option value="374">VINHOMES SKY LAKE</option>
<option value="375">VINHOMES GARDENIA</option>
<option value="376">FIVE STAR MỸ ĐÌNH</option>
<option value="377">RICE HOME SÔNG HỒNG</option>
<option value="378">PANDORA 53 TRIỀU KHÚC</option>
<option value="379">VINHOMES SMART CITY</option>
<option value="380">VINHOMES GREEN BAY MỄ TRÌ</option>
<option value="381">XUÂN PHƯƠNG TASCO</option>
<option value="382">HOA VIÊN VILLAS</option>
<option value="383">LAVENDER 124 VĨNH TUY</option>
<option value="384">STARLAKE HÀ NỘI</option>
<option value="385">LÂM VIÊN VILLAS</option>
<option value="386">FLC GARDEN CITY</option>
<option value="387">ROSE VALLEY</option>
<option value="388">LỘC NINH SINGASHINE</option>
<option value="389">CONSTREXIM COMPLEX</option>
<option value="390">KHU ĐÔ THỊ VĂN LA - VĂN KHÊ</option>
<option value="391">HABICO TOWER</option>
<option value="392">THÀNH PHỐ GIAO LƯU</option>
<option value="393">KHU CHỨC NĂNG ĐÔ THỊ AO SÀO</option>
<option value="394">THE MANOR CENTRAL PARK</option>
<option value="395">BERRIVER LONG BIÊN</option>
<option value="396">KHU NHÀ Ở PHÚ THƯỢNG</option>
<option value="397">PARKCITY HÀ NỘI</option>
<option value="398">KHU ĐÔ THỊ KIM CHUNG - DI TRẠCH</option>
<option value="399">KHU NGOẠI GIAO ĐOÀN</option>
<option value="400">KHU ĐÔ THỊ MỚI CỔ NHUẾ</option>
<option value="401">KHU ĐÔ THỊ MỖ LAO</option>
<option value="402">KHU ĐÔ THỊ MỚI XA LA</option>
<option value="403">KHU ĐÔ THỊ MỚI PHÙNG KHOANG</option>
<option value="404">KHU ĐÔ THỊ MỚI TÂN TÂY ĐÔ</option>
<option value="405">KHU ĐÔ THỊ SPLENDORA AN KHÁNH</option>
<option value="406">THÁP DOANH NHÂN TOWER</option>
<option value="407">TRƯƠNG ĐỊNH COMPLEX</option>
<option value="408">HIM LAM THẠCH BÀN 2</option>
<option value="409">TABUDEC PLAZA</option>
<option value="410">TỨ HIỆP PLAZA</option>
<option value="411">FLC GREEN HOME</option>
<option value="412">GEMEK PREMIUM</option>
<option value="414">GOLDEN FIELD MỸ ĐÌNH</option>
<option value="415">VALENCIA GARDEN</option>
<option value="416">IMPERIAL PLAZA</option>
<option value="417">ECO SPRING</option>
<option value="418">HAPPY STAR TOWER</option>
<option value="419">ATHENA COMPLEX</option>
<option value="420">PARAGON TOWER</option>
<option value="421">GOLDSEASON</option>
<option value="422">HH2 LINH ĐÀM</option>
<option value="423">KHU DI DÂN ĐỀN LỪ III</option>
<option value="431">VINHOMES NGUYỄN CHÍ THANH</option>
<option value="432">KHU DU LỊCH SINH THÁI TUẦN CHÂU HÀ NỘI</option>
<option value="433">MIPEC RIVERSIDE</option>
<option value="438">KHU CÔNG NGHIỆP BẮC PHÚ CÁT</option>
<option value="449">VINHOMES METROPOLIS</option>
<option value="450">VINHOMES D'CAPITALE</option>
<option value="451">PARK VIEW RESIDENCE</option>
<option value="452">FIVE STAR KIM GIANG</option>
<option value="453">THE GOLDEN AN KHÁNH</option>
<option value="454">ĐỒNG PHÁT PARK VIEW TOWER</option>
<option value="455">MỸ ĐÌNH PEARL</option>
<option value="456">THANG LONG NUMBER ONE</option>
<option value="457">HÒA BÌNH GREEN CITY</option>
<option value="458">CHUNG CƯ TINCOM PHÁP VÂN</option>
<option value="459">GOLDEN LAND</option>
<option value="460">GOLDEN PALACE</option>
<option value="461">DOLPHIN PLAZA</option>
<option value="462">HONG KONG TOWER</option>
<option value="471">THE K PARK</option>
<option value="563">GAMUDA LAKES</option>
<option value="575">HOÀNG THÀNH TOWER</option>
<option value="585">LA CASTA VĂN PHÚ</option>
<option value="587">LePARC by Gamuda</option>
<option value="589">PENTSTUDIO</option>
<option value="590">AN PHÚ SHOP VILLA</option>
<option value="592">HC GOLDEN CITY</option>
<option value="594">PVI TÂY HỒ TÂY</option>
<option value="596">KHU CÔNG NGHIỆP PHÚ NGHĨA</option>
<option value="601">KHU NHÀ Ở V5 V6</option>
<option value="606">HDI HOMES VŨ PHẠM HÀM</option>
<option value="609">GELEX TOWER</option>
<option value="612">KDC CHỢ RẠCH KIẾN</option>
<option value="633">KHU CÔNG NGHIỆP QUANG MINH</option>
<option value="641">KCN THẠCH THẤT - QUỐC OAI</option>
<option value="642">KHU CÔNG NGHIỆP NỘI BÀI</option>
<option value="643">KHU CÔNG NGHIỆP BẮC PHÚ CÁT - HÀ NỘI</option>
<option value="668">PREMIER VILLAGE PHÚ QUỐC</option>
<option value="687">DANANG BEACH RESORT</option>
<option value="690">KHU NHÀ Ở HƯNG THỊNH</option>
<option value="698">HẢI PHÁT COMPLEX</option>
<option value="701">FLC PREMIER PARK ĐẠI MỖ</option>
<option value="703">KHU ĐÔ THỊ THIÊN MỸ LỘC</option>
<option value="712">KHU ĐÔ THỊ PHÚ CÁT CITY</option>
<option value="714">KHU ĐÔ THỊ ĐẠI HỌC VÂN CANH</option>
<option value="734">GOLDEN CITY AN GIANG</option>
<option value="745">THE LANCASTER HÀ NỘI</option>
<option value="746">HAPRO BUILDING</option>
<option value="748">TRUNG TÂM THƯƠNG MẠI TSQ</option>
<option value="749">THANH NIÊN PLAZA</option>
<option value="753">HANOI DAEWOO HOTEL</option>
<option value="754">TRUNG TÂM THƯƠNG MẠI CHỢ MƠ</option>
<option value="755">GRAND PLAZA</option>
<option value="757">CHUNG CƯ 57 VŨ TRỌNG PHỤNG</option>
<option value="759">TTTM DỊCH VỤ HẠ ĐÌNH</option>
<option value="761">TRUNG TÂM THƯƠNG MẠI KHƯƠNG ĐÌNH</option>
<option value="763">TTTM VÀ PHỐ CHỢ ĐÔ NGHĨA</option>
<option value="769">PHỐ THƯƠNG MẠI TRẢNG NHẬT</option>
<option value="775">VTC ONLINE BUILDING</option>
<option value="776">PRIME CENTRE</option>
<option value="777">TÒA NHÀ CTY CPXD SỐ 1 HN</option>
<option value="778">CDC BUILDING</option>
<option value="779">TÒA NHÀ THÁI BÌNH</option>
<option value="780">TÒA NHÀ 14 LÝ NAM ĐẾ</option>
<option value="781">V BUILDING</option>
<option value="782">HANOITOURIST BUILDING</option>
<option value="783">VID TOWER 1</option>
<option value="784">NAM HẢI LAKEVIEW</option>
<option value="785">NAM CƯỜNG BUILDING</option>
<option value="786">TÒA NHÀ ICD</option>
<option value="787">LILAMA 10</option>
<option value="788">HH3 TOWER</option>
<option value="789">TRÚC BẠCH BUILDING</option>
<option value="790">TÒA NHÀ HIPT</option>
<option value="791">VINAFOR</option>
<option value="792">COMA BUILDING</option>
<option value="793">TÒA NHÀ TÂN Á ĐẠI THÀNH</option>
<option value="794">MECANIMEX BUILDING</option>
<option value="795">TÒA NHÀ NGUYỄN KHUYẾN</option>
<option value="797">THÀNH ĐÔNG BUILDING</option>
<option value="798">TID TOWER</option>
<option value="799">TOSERCO BUILDING</option>
<option value="800">VINACONEX TOWER</option>
<option value="801">HITTC BUILDING</option>
<option value="802">HAREC BUILDING</option>
<option value="808">TÒA NHÀ FORD THĂNG LONG</option>
<option value="810">HÀN VIỆT TOWER</option>
<option value="812">VG BUILDING</option>
<option value="813">LILAMA 124 MINH KHAI</option>
<option value="860">LẠC HỒNG LOTUS HẠ LONG</option>
<option value="861">THỐNG NHẤT COMPLEX</option>
<option value="862">KINGSWAY TOWER</option>
<option value="864">THE EMERALD</option>
<option value="866">VINCITY HÀ TĨNH</option>
<option value="872">CARILLON 7</option>
<option value="873">MULBERRY LANE</option>
<option value="874">SEASONS AVENUE</option>
<option value="875">AN BÌNH 1</option>
<option value="881">N01-D17 DUY TÂN</option>
<option value="883">BELLA VIDA</option>
<option value="884">THANH XUÂN COMPLEX</option>
<option value="885">CHUNG CƯ C51 BỘ CÔNG AN</option>
<option value="886">ICID COMPLEX</option>
<option value="889">HÀ ĐÔNG PARK VIEW</option>
<option value="892">GREEN HOUSE</option>
<option value="894">SKY CENTRAL</option>
<option value="895">UDIC WESTLAKE</option>
<option value="897">GREEN PARK TRẦN THỦ ĐỘ</option>
<option value="899">XUÂN MAI COMPLEX</option>
<option value="900">GREEN TOWER SÀI ĐỒNG</option>
<option value="904">CHUNG CƯ NO-08 GIANG BIÊN</option>
<option value="907">SUNSHINE CITY</option>
<option value="908">SÀI ĐỒNG LAKE VIEW</option>
<option value="910">C7 GIẢNG VÕ</option>
<option value="912">KHU TÁI ĐỊNH CƯ XUÂN LA</option>
<option value="913">CẦU GIẤY CENTER POINT</option>
<option value="915">NHÀ Ở XÃ HỘI @HOME</option>
<option value="920">HH1 MỄ TRÌ HẠ</option>
<option value="921">IRIS GARDEN</option>
<option value="922">TECCO TỨ HIỆP</option>
<option value="926">CHELSEA RESIDENCES</option>
<option value="929">STARTUP TOWER</option>
<option value="930">HDI TOWER</option>
<option value="941">STELLAR GARDEN</option>
<option value="949">ROMAN PLAZA</option>
<option value="955">CT2 YÊN NGHĨA</option>
<option value="956">DSD BUILDING</option>
<option value="962">GELEXIA RIVERSIDE</option>
<option value="963">HANHUD HOÀNG QUỐC VIỆT</option>
<option value="966">CHUNG CƯ 60 HOÀNG QUỐC VIỆT</option>
<option value="967">CHUNG CƯ 789 XUÂN ĐỈNH</option>
<option value="972">CĂN HỘ DỊCH VỤ CAO CẤP NHẬT BẢN</option>
<option value="973">CT1 THẠCH BÀN</option>
<option value="978">DREAM LAND PLAZA</option>
<option value="982">N03-T7 NGOẠI GIAO ĐOÀN</option>
<option value="985">T&amp;T RIVERVIEW</option>
<option value="992">RICE CITY LINH ĐÀM</option>
<option value="993">ECOLIFE TÂY HỒ</option>
<option value="997">N03 -T8 NGOẠI GIAO ĐOÀN</option>
<option value="998">N03-T5 NGOẠI GIAO ĐOÀN</option>
<option value="999">N03-T3&amp;T4 NGOẠI GIAO ĐOÀN</option>
<option value="1000">N03-T3&amp;T4 NGOẠI GIAO ĐOÀN</option>
<option value="1001">N03-T2 NGOẠI GIAO ĐOÀN</option>
<option value="1002">N03-T1 NGOẠI GIAO ĐOÀN</option>
<option value="1003">N02-T3 NGOẠI GIAO ĐOÀN</option>
<option value="1004">N02-T2 NGOẠI GIAO ĐOÀN</option>
<option value="1005">N02-T1 NGOẠI GIAO ĐOÀN</option>
<option value="1006">N01-T8 NGOẠI GIAO ĐOÀN</option>
<option value="1007">N01-T6 NGOẠI GIAO ĐOÀN</option>
<option value="1008">N01-T5 NGOẠI GIAO ĐOÀN</option>
<option value="1009">N01-T4 NGOẠI GIAO ĐOÀN</option>
<option value="1010">N01-T3 NGOẠI GIAO ĐOÀN</option>
<option value="1011">N01-T2 NGOẠI GIAO ĐOÀN</option>
<option value="1012">N01-T1 NGOẠI GIAO ĐOÀN</option>
<option value="1013">THE TWO RESIDENCE - GAMUDA GARDEN</option>
<option value="1014">THE ONE RESIDENCE - GAMUDA GARDEN</option>
<option value="1015">CHUNG CƯ 622 MINH KHAI</option>
<option value="1016">CT4 VIMECO II</option>
<option value="1017">CT2 XUÂN PHƯƠNG</option>
<option value="1023">THE GOLDEN AN KHÁNH 32T</option>
<option value="1024">FLC GREEN HOME 18 PHẠM HÙNG</option>
<option value="1029">CHUNG CƯ CT3 YÊN NGHĨA</option>
<option value="1030">CC1 HÀ ĐÔ PARKSIDE</option>
<option value="1040">CHUNG CƯ 282 NGUYỄN HUY TƯỞNG</option>
<option value="1044">VINHOMES METROPOLIS - LIỄU GIAI</option>
<option value="1045">CHUNG CƯ 122 VĨNH TUY</option>
<option value="1049">CHUNG CƯ THÔNG TẤN XÃ VIỆT NAM</option>
<option value="1055">CHUNG CƯ 379 ĐỘI CẤN</option>
<option value="1056">RUBY CITY</option>
<option value="1058">CHUNG CƯ QMS</option>
<option value="1061">ECOLIFE CAPITOL</option>
<option value="1062">CHUNG CƯ TĐC HOÀNG CẦU</option>
<option value="1069">DIAMOND LOTUS PHÚC KHANG</option>
<option value="1071">YÊN HÒA CONDOMINIUM</option>
<option value="1072">HAMILTON COMPLEX</option>
<option value="1073">NEW SPACE GIANG BIÊN</option>
<option value="1077">NHÀ Ở XÃ HỘI ĐỒNG MÔ</option>
<option value="1078">SUNSHINE PALACE</option>
<option value="1080">TOKYO TOWER</option>
<option value="1081">PVV-VINAPHARM 60B NGUYỄN HUY TƯỞNG</option>
<option value="1083">VICEM COMATCE TOWER</option>
<option value="1084">THE PRIDE</option>
<option value="1085">ECO GREEN CITY</option>
<option value="1089">HAPPY HOUSE 296 LĨNH NAM</option>
<option value="1090">LẠC HỒNG WESTLAKE</option>
<option value="1091">84 THỢ NHUỘM - HANOI APARTMENT CENTER</option>
<option value="1092">TIMES TOWER - HACC1 COMPLEX BUILDING</option>
<option value="1094">HATECO HOÀNG MAI</option>
<option value="1110">ECOHOME 2</option>
<option value="1111">IMPERIA GARDEN</option>
<option value="1113">HOÀNG NGÂN PLAZA</option>
<option value="1120">CHUNG CƯ X1-26 LIỄU GIAI</option>
<option value="1121">THE GARDEN HILLS - 99 TRẦN BÌNH</option>
<option value="1123">CAO ỐC BÌNH ĐÔNG XANH</option>
<option value="1124">CT36 - DREAM HOME</option>
<option value="1126">SCITECH TOWER</option>
<option value="1127">ECOHOME 1</option>
<option value="1128">THÀNH AN TOWER</option>
<option value="1136">CHUNG CƯ ORIENTAL WESTLAKE</option>
<option value="1141">VIỆT ĐỨC COMPLEX</option>
<option value="1142">PCC1 COMPLEX</option>
<option value="1143">HH1 LINH ĐÀM</option>
<option value="1144">KHU NHÀ Ở QUÂN ĐỘI K35 TÂN MAI</option>
<option value="1151">NEW HORIZON CITY - 87 LĨNH NAM</option>
<option value="1159">CHUNG CƯ MINI CỰ LỘC</option>
<option value="1161">CHUNG CƯ B7 - B10 KIM LIÊN</option>
<option value="1163">CHUNG CƯ HANCOM</option>
<option value="1165">CHUNG CƯ TÂY NAM ĐH THƯƠNG MẠI</option>
<option value="1168">CHUNG CƯ 30 PHẠM VĂN ĐỒNG</option>
<option value="1169">HÒA PHÁT 70 NDC TOWER</option>
<option value="1178">HELIOS TOWER 75 TAM TRINH</option>
<option value="1182">KHU ĐÔ THỊ KIM VĂN - KIM LŨ (GOLDEN SILK)</option>
<option value="1188">CHUNG CƯ CT6 CONSTREXIM</option>
<option value="1189">CHUNG CƯ 120 HOÀNG QUỐC VIỆT</option>
<option value="1195">CHUNG CƯ ĐÀO DUY TỪ</option>
<option value="1196">VP4 LINH ĐÀM</option>
<option value="1194">CHUNG CƯ HOA LƯ</option>
<option value="1201">HH3 LINH ĐÀM</option>
<option value="1202">BÌNH VƯỢNG TOWER</option>
<option value="1208">DỰ ÁN VIỆN BỎNG LÊ HỮU TRÁC</option>
<option value="1209">B6 GIẢNG VÕ</option>
<option value="1213">SDU - 143 TRẦN PHÚ</option>
<option value="1218">CT3 TÂY NAM LINH ĐÀM</option>
<option value="1220">CHUNG CƯ 113 TRUNG KÍNH</option>
<option value="1222">CHUNG CƯ ĐÔNG ĐÔ</option>
<option value="1223">CHUNG CƯ 96 ĐỊNH CÔNG</option>
<option value="1224">CT2 TRUNG VĂN - VINACONEX 3</option>
<option value="1226">CHUNG CƯ NEWTATCO</option>
<option value="1227">TÒA NHÀ LICOGI 18</option>
<option value="1230">DIAMOND BLUE 69 TRIỀU KHÚC</option>
<option value="1231">HH4 LINH ĐÀM</option>
<option value="1235">AN BÌNH TOWER</option>
<option value="1236">VP2 LINH ĐÀM</option>
<option value="1239">CHUNG CƯ CẦU TIÊN</option>
<option value="1240">AN LẠC - PHÙNG KHOANG</option>
<option value="1241">SAPPHIRE PALACE</option>
<option value="1247">CHUNG CƯ AN LẠC</option>
<option value="1252">CHUNG CƯ BIỂN BẮC</option>
<option value="1255">C17 BỘ CÔNG AN</option>
<option value="1263">TOÀ NHÀ COWAELMIC</option>
<option value="1265">CHUNG CƯ CIENCO1</option>
<option value="1277">CHUNG CƯ 183 HOÀNG VĂN THÁI</option>
<option value="1282">INTRACOM 6</option>
<option value="1283">INTRACOM 208</option>
<option value="1284">INTRACOM 3</option>
<option value="1285">CT NUMBER ONE</option>
<option value="1290">D22 BỘ TƯ LỆNH BIÊN PHÒNG</option>
<option value="1296">SUNRISE BUILDING 3</option>
<option value="1299">CHUNG CƯ VINACONEX 21</option>
<option value="1303">CHUNG CƯ NGÔ GIA TỰ</option>
<option value="1307">CHUNG CƯ 130 NGUYỄN ĐỨC CẢNH</option>
<option value="1310">CĂN HỘ LINH TRUNG</option>
<option value="1312">CHUNG CƯ BOOYOUNG</option>
<option value="1314">LOTUS LAKE VIEW</option>
<option value="1316">DIAMOND FLOWER TOWER</option>
<option value="1323">CHUNG CƯ VIỆN 103</option>
<option value="1325">SOUTH TOWER</option>
<option value="1326">CHUNG CƯ SỐ 6 ĐỘI NHÂN</option>
<option value="1329">VP6 LINH ĐÀM</option>
<option value="1334">VOV MỄ TRÌ</option>
<option value="1337">THĂNG LONG VICTORY</option>
<option value="1339">CHUNG CƯ SÔNG ĐÀ 7</option>
<option value="1341">CHUNG CƯ YÊN HÒA THĂNG LONG</option>
<option value="1342">SKY PARK RESIDENCE</option>
<option value="1343">NEW SKYLINE</option>
<option value="1345">CHUNG CƯ XPHOMES</option>
<option value="1349">CHUNG CƯ CT3 LÊ ĐỨC THỌ</option>
<option value="1351">AN LẠC - NAM LA KHÊ</option>
<option value="1357">GARDEN COURT 1</option>
<option value="1369">CHUNG CƯ PACKEXIM</option>
<option value="1370">CHUNG CƯ N105 NGUYỄN PHONG SẮC</option>
<option value="1372">TÒA NHÀ VINACONEX 1</option>
<option value="1374">MD COMPLEX MỸ ĐÌNH</option>
<option value="1375">CHUNG CƯ 15-17 NGỌC KHÁNH</option>
<option value="1376">CHUNG CƯ GOLDEN WEST</option>
<option value="1381">CHUNG CƯ VƯỜN XUÂN - 71 NGUYỄN CHÍ THANH</option>
<option value="1383">WATERMARK</option>
<option value="1385">STAR TOWER 283 KHƯƠNG TRUNG</option>
<option value="1389">HẠ ĐÌNH TOWER</option>
<option value="1390">CHUNG CƯ MINI KIM CƯƠNG XUÂN ĐỈNH</option>
<option value="1396">VP3 LINH ĐÀM</option>
<option value="1397">VP5 LINH ĐÀM</option>
<option value="1399">TÂY HÀ TOWER</option>
<option value="1400">VC7 HOUSING COMPLEX</option>
<option value="1401">RIVERSIDE TOWER</option>
<option value="1402">FAFILM - VNT TOWER</option>
<option value="1403">C37 BỘ CÔNG AN - BẮC HÀ TOWER</option>
<option value="1404">HH2 - BẮC HÀ</option>
<option value="1410">D’. LE PONT D’OR - HOÀNG CẦU</option>
<option value="1411">PLATINUM RESIDENCES</option>
<option value="1413">SKYVIEW TRẦN THÁI TÔNG</option>
<option value="1416">SOMERSET HÒA BÌNH</option>
<option value="1417">VINACONEX 7</option>
<option value="1419">TỔ HỢP CHUNG CƯ THỦY LỢI TOWER</option>
<option value="1422">RAINBOW LINH ĐÀM</option>
<option value="1423">PHÚC THỊNH TOWER</option>
<option value="1426">HEI TOWER</option>
<option value="1432">SPRING HOME</option>
<option value="1434">TÂY HỒ RESIDENCE</option>
<option value="1439">PHÚ GIA RESIDENCE</option>
<option value="1441">GREEN PARK TOWER</option>
<option value="1442">STAR TOWER (TÒA THÁP NGÔI SAO)</option>
<option value="1443">CHUNG CƯ 89 PHÙNG HƯNG</option>
<option value="1445">KHU ĐÔ THỊ MỚI ĐẠI THANH</option>
<option value="1448">XUÂN MAI PARK STATE</option>
<option value="1452">SAMSORA PREMIER</option>
<option value="1453">MỸ SƠN TOWER</option>
<option value="1455">FLC COMPLEX 36 PHẠM HÙNG</option>
<option value="1456">D’. PALAIS DE LOUIS - NGUYỄN VĂN HUYÊN</option>
<option value="1460">GREEN STARS</option>
<option value="1461">THANH ĐA VIEW</option>
<option value="1463">HA DO PARK VIEW</option>
<option value="1475">VIMECO I - PHẠM HÙNG</option>
<option value="1482">TIG TOWER</option>
<option value="1490">NGUYỄN CHÁNH HÀ ĐÔNG</option>
<option value="1491">CHUNG CƯ SỐ 7 TRẦN PHÚ</option>
<option value="1493">FIVE STARS WESTLAKE</option>
<option value="1506">LOTUS COMPLEX HH1</option>
<option value="1513">C3 TOWER - GOLDEN PALACE</option>
<option value="1515">CHUNG CƯ 25 TÂN MAI</option>
<option value="1517">KHU NHÀ Ở CAO TẦNG 102 TRƯỜNG CHINH</option>
<option value="1518">MỸ ĐÌNH PLAZA</option>
<option value="1520">GEMEK TOWER</option>
<option value="1522">CAPITAL GARDEN 102 TRƯỜNG CHINH KINH ĐÔ</option>
<option value="1523">CHUNG CƯ 229 PHỐ VỌNG</option>
<option value="1524">CHUNG CƯ BỘ TỔNG THAM MƯU</option>
<option value="1525">CHUNG CƯ 16B NGUYỄN THÁI HỌC</option>
<option value="1538">CHUNG CƯ PHÚ ĐẠT</option>
<option value="1547">CHUNG CƯ FIVE STARS - AN KHÁNH</option>
<option value="1554">KHU NHÀ Ở VŨ NGỌC PHAN</option>
<option value="1555">CHUNG CƯ 141 TRƯƠNG ĐỊNH</option>
<option value="1556">CHUNG CƯ 45 NGUYỄN SƠN</option>
<option value="1558">CHUNG CƯ 72 QUAN NHÂN</option>
<option value="1565">KHU NHÀ Ở CHO CÔNG NHÂN ĐÔNG ANH</option>
<option value="1566">KHU NHÀ Ở KINH DOANH DỊCH VỌNG</option>
<option value="1567">CHUNG CƯ HOÀNG QUY</option>
<option value="1568">CHUNG CƯ, VĂN PHÒNG 222 ĐỘI CẤN</option>
<option value="1574">CHUNG CƯ 134 QUÁN THÁNH</option>
<option value="1575">CHUNG CƯ AN LẠC - MỸ ĐÌNH</option>
<option value="1576">CHUNG CƯ MÙA XUÂN</option>
<option value="1577">CHUNG CƯ CÁC KCN - MÊ LINH</option>
<option value="1579">KHU ĐÔ THỊ VĨNH HOÀNG</option>
<option value="1580">HÀ NỘI CENTER POINT</option>
<option value="1581">CHUNG CƯ 187 TÂY SƠN</option>
<option value="1589">KHU NHÀ Ở 44 TRIỀU KHÚC</option>
<option value="1590">CHUNG CƯ D2 GIẢNG VÕ</option>
<option value="1591">CHUNG CƯ B1 GIẢNG VÕ</option>
<option value="1594">LÊ VĂN LƯƠNG RESIDENTIALS</option>
<option value="1595">SÔNG HỒNG PARK VIEW</option>
<option value="1596">CHCC 257 GIẢI PHÓNG</option>
<option value="1597">TỔ HỢP 25 LẠC TRUNG</option>
<option value="1598">STARCITY CENTER</option>
<option value="1600">SÔNG ĐÀ HÀ ĐÔNG TOWER</option>
<option value="1601">STAR CITY LÊ VĂN LƯƠNG</option>
<option value="1602">NHÀ Ở TỔNG CỤC 5 - BỘ CÔNG AN</option>
<option value="1604">C14 - BỘ CÔNG AN</option>
<option value="1605">LÀNG BIDV SCIENCO 5 MÊ LINH</option>
<option value="1611">RAINBOW BUILDING</option>
<option value="1613">EUROWINDOW MULTI COMPLEX</option>
<option value="1615">KHU NHÀ Ở HÀO NAM</option>
<option value="1617">NAM ĐÔ COMPLEX 609 TRƯƠNG ĐỊNH</option>
<option value="1628">TÒA NHÀ 282 LĨNH NAM</option>
<option value="1629">TÒA NHÀ 101 LÁNG HẠ</option>
<option value="1630">TỔ HỢP NHÀ CAO TẦNG PHÚ MỸ</option>
<option value="1659">N04 - KĐT ĐÔNG NAM TRẦN DUY HƯNG</option>
<option value="1660">SKY CITY TOWERS-88 LÁNG HẠ</option>
<option value="1661">HOÀNG SÂM - 151 HOÀNG QUỐC VIỆT</option>
<option value="1662">DAEWOO CLEVE</option>
<option value="1663">CHUNG CƯ X2 MỸ ĐÌNH</option>
<option value="1664">TÒA NHÀ 131 PHỐ THÁI HÀ</option>
<option value="1665">HÒA BÌNH GREEN APARTMENT</option>
<option value="1666">CT2 VIETTEL TRUNG VĂN</option>
<option value="1667">MEGASTAR DOMINIUM C2 XUÂN ĐỈNH</option>
<option value="1668">HYUNDAI HILLSTATE</option>
<option value="1673">FIVE STAR RESIDENT</option>
<option value="1674">RUBY CT3 PHÚC LỢI</option>
<option value="1676">HÀ NỘI HOMELAND</option>
<option value="1677">THE SPARKS</option>
<option value="1684">NHÀ Ở CÁN BỘ CHIẾN SỸ CÔNG AN GIA LÂM</option>
<option value="1689">Liền Kề Shophouse Him Lam Vạn Phúc</option>
<option value="1691">NHÀ Ở LIỀN KẾ LỘC NINH</option>
