<option value="0">Chọn Dự án</option>
<option value="624">TECCO TRƯỜNG THỊNH</option>
<option value="656">VINPEARL CỬA HỘI</option>
<option value="693">VINH PLAZA</option>
<option value="695">T &amp; T VICTORIA</option>
<option value="700">GOLDEN CITY 12</option>
<option value="890">BẢO SƠN COMPLEX</option>
<option value="896">ARITA HOME</option>
<option value="911">CHUNG CƯ SAO NGHỆ</option>
<option value="925">CHUNG CƯ KIM TRƯỜNG THI</option>
<option value="954">CỬA TIỀN HOME</option>
<option value="964">MƯỜNG THANH CỬA ĐÔNG</option>
<option value="1152">GREEN VIEW TOWER</option>
<option value="1206">CHUNG CƯ TÂN THỊNH</option>
<option value="1207">TECCO TOWER</option>
