<option value="0">Chọn Dự án</option>
<option value="425">ZEN TOWER</option>
<option value="427">VICTORIA VILLAGE</option>
<option value="429">THĂNG LONG HOME HƯNG PHÚ</option>
<option value="437">KHU CÔNG NGHIỆP PHONG PHÚ</option>
<option value="463">NEW CITY THỦ THIÊM</option>
<option value="464">THE GARDEN BAY</option>
<option value="465">JAMILA KHANG ĐIỀN</option>
<option value="466">WATER BAY NOVALAND</option>
<option value="467">SÀI GÒN GATEWAY</option>
<option value="468">VENTOSA</option>
<option value="469">STARLIGHT RIVERSIDE</option>
<option value="470">TÔ KÝ TOWER</option>
<option value="472">CHARMINGTON IRIS</option>
<option value="473">ĐỨC LONG WESTERN PARK</option>
<option value="474">REPUBLIC PLAZA</option>
<option value="475">THE GRANDE</option>
<option value="476">MIDTOWN PHÚ MỸ HƯNG</option>
<option value="477">THE WESTERN CAPITAL</option>
<option value="478">LUXGARDEN</option>
<option value="479">ĐẠT GIA CENTRE POINT THỦ ĐỨC</option>
<option value="480">TOPAZ HOME</option>
<option value="481">D-VELA</option>
<option value="482">MASTERI MILLENNIUM</option>
<option value="483">FELIZ EN VISTA</option>
<option value="484">ELITE PARK</option>
<option value="485">HEAVEN RIVERVIEW</option>
<option value="486">SAIGON ROYAL RESIDENCE</option>
<option value="487">SÀI GÒN MÊ LINH TOWER</option>
<option value="488">TULIP TOWER</option>
<option value="489">RIVER CITY</option>
<option value="490">BOTANICA PREMIER</option>
<option value="491">VIVA RIVERSIDE</option>
<option value="492">CENTA PARK TÂN BÌNH</option>
<option value="493">THE AVILA</option>
<option value="494">CĂN HỘ AURIS CITY</option>
<option value="495">CĂN HỘ RIVA PARK</option>
<option value="496">SUNRISE RIVERSIDE</option>
<option value="497">ESTELLA HEIGHTS</option>
<option value="498">THE KRISTA</option>
<option value="499">BÌNH AN PEARL</option>
<option value="500">THE SUN AVENUE</option>
<option value="505">REMAX PLAZA</option>
<option value="506">THE TRESOR</option>
<option value="507">ANGIA STAR</option>
<option value="508">SOHO RIVERVIEW</option>
<option value="509">THE ASCENT</option>
<option value="510">VISTA VERDE</option>
<option value="511">GARDEN PLAZA 2</option>
<option value="512">ICON 56</option>
<option value="513">THE PARK RESIDENCE</option>
<option value="514">SUNVIEW TOWN</option>
<option value="515">ĐẠT GIA RESIDENCE THỦ ĐỨC</option>
<option value="516">CENTRAL PLAZA - 91 PHẠM VĂN HAI</option>
<option value="517">CARILLON APARTMENT</option>
<option value="518">CITY GATE TOWERS 2</option>
<option value="519">IMPERIA AN PHÚ</option>
<option value="520">THỦ THIÊM STAR</option>
<option value="521">SÔNG ĐÀ RIVERSIDE</option>
<option value="522">REGENCY PARK</option>
<option value="523">TROPIC GARDEN</option>
<option value="524">CANTAVIL AN PHÚ - CANTAVIL PREMIER</option>
<option value="525">SC VIVOCITY</option>
<option value="526">VINCOM CENTER</option>
<option value="527">PALM CITY</option>
<option value="528">THE PEGA SUITE</option>
<option value="529">SENTURIA VƯỜN LÀI</option>
<option value="530">EMPIRE CITY THỦ THIÊM</option>
<option value="531">BELLA VISTA CITY</option>
<option value="532">HARBOR CITY</option>
<option value="533">THỚI AN CITY</option>
<option value="534">VINHOMES GOLDEN RIVER BA SON</option>
<option value="535">KHU ĐÔ THỊ LAKEVIEW CITY</option>
<option value="536">NAM PHÁT RIVERSIDE</option>
<option value="537">KHU DÂN CƯ CAMELLIA GARDEN</option>
<option value="538">THÁI DƯƠNG LUXURY</option>
<option value="539">CITI BELLA</option>
<option value="540">THE STARS VILLAGE</option>
<option value="541">PARK RIVERSIDE TÂN CẢNG</option>
<option value="542">KHU DÂN CƯ VHOME</option>
<option value="543">KHU ĐÔ THỊ GS METROCITY</option>
<option value="544">VẠN PHÚC RIVERSIDE CITY</option>
<option value="545">LA ASTORIA</option>
<option value="546">TÊN LỬA RESIDENCE</option>
<option value="547">DRAGON PARC</option>
<option value="548">KHU BIỆT THỰ MỸ VĂN</option>
<option value="549">BIỆT THỰ SÔNG ÔNG LỚN</option>
<option value="550">NAM SÀI GÒN RIVERSIDE</option>
<option value="551">OSIMI TOWER</option>
<option value="552">TOPAZ ELITE</option>
<option value="553">WATERINA SUITES</option>
<option value="554">SAIGON MYSTERY VILLAS</option>
<option value="557">VICTORIA VILLAGE</option>
<option value="560">CENTANA ĐIỀN PHÚC THÀNH</option>
<option value="562">MOONLIGHT RESIDENCES</option>
<option value="566">CĂN HỘ RICHSTAR</option>
<option value="568">MELOSA GARDEN</option>
<option value="571">THE PARK AVENUE</option>
<option value="572">MASTERI THẢO ĐIỀN</option>
<option value="573">PEARL PLAZA</option>
<option value="574">SAIGON ONE TOWER</option>
<option value="576">C.T PLAZA VÕ VĂN KIỆT</option>
<option value="577">HÀ ĐÔ AIRPORT BUILDING</option>
<option value="578">TPA BUILDING</option>
<option value="579">SUNWAH TOWER</option>
<option value="581">CASA GARDEN</option>
<option value="582">KHU CÔNG NGHIỆP TÂN TẠO</option>
<option value="584">ZEN TOWER</option>
<option value="588">MÊ LINH POINT TOWER</option>
<option value="595">VILLA E6 QUẬN 2</option>
<option value="603">CITADEL RESIDENCE</option>
<option value="618">MONADA KHANG ĐIỀN</option>
<option value="607">MỸ TÚ 3</option>
<option value="610">LUCKY GARDEN</option>
<option value="620">KDC AN THỊNH BÀ ĐIỂM</option>
<option value="613">GREEN LOTUS RESIDENT</option>
<option value="614">THE POINT QUẬN 7</option>
<option value="636">KHU CÔNG NGHIỆP TÂN BÌNH</option>
<option value="689">FELIX HOMES</option>
<option value="691">EHOME S</option>
<option value="696">LAVIDA PLUS</option>
<option value="697">GLENWOOD MAISON THẢO ĐIỀN</option>
<option value="704">NAM PHONG ECO PARK</option>
<option value="740">KHU ĐÔ THỊ BẾN THÀNH TÂY BẮC</option>
<option value="747">THIÊN SƠN PLAZA - HỒ CHÍ MINH</option>
<option value="750">SÀI GÒN PARAGON</option>
<option value="751">VINCOM CENTER TP HCM</option>
<option value="752">HÙNG VƯƠNG PLAZA</option>
<option value="758">TTTM – DV - VP HÀNG XANH</option>
<option value="764">PARKLAND APARTMENTS</option>
<option value="767">CỐNG QUỲNH PLAZA</option>
<option value="772">THE NAVITA</option>
<option value="773">IBC BUILDING</option>
<option value="774">C.T PLAZA TÂN SƠN NHẤT</option>
<option value="796">CITILIGHT TOWER</option>
<option value="803">IMG BUILDING</option>
<option value="804">SCETPA BUILDING</option>
<option value="805">SAMCO BUILDING</option>
<option value="806">THE ONE SÀI GÒN</option>
<option value="807">VINACONEX BUILDING</option>
<option value="809">MINH LONG TOWER</option>
<option value="811">LIM TOWER</option>
<option value="814">THẢO ĐIỀN BUILDING</option>
<option value="815">QMOBILE TOWER</option>
<option value="816">COMPA TOWER</option>
<option value="817">EBM BUILDING</option>
<option value="818">GIA THY BUILDING</option>
<option value="819">PARKSIMEX BUILDING</option>
<option value="820">LUTACO TOWER</option>
<option value="821">HEMERA BUILDING</option>
<option value="822">RESCO BUILDING</option>
<option value="823">SAIGON TRADE CENTER</option>
<option value="824">TÒA NHÀ HÀ PHAN</option>
<option value="825">ALPHA TOWER</option>
<option value="826">PVC SAI GON BUILDING</option>
<option value="827">LIEN HOA BUILDING</option>
<option value="828">NGỌC ĐÔNG DƯƠNG BUILDING</option>
<option value="829">VMG BUILDING</option>
<option value="830">HUD BUILDING</option>
<option value="831">AVALON SAIGON APARTMENTS</option>
<option value="832">HCMC LOTTERY TOWER</option>
<option value="833">ETOWN BUILDING</option>
<option value="834">PEACE BUILDING</option>
<option value="835">LUCKY HOUSE</option>
<option value="836">ARIRANG BUILDING</option>
<option value="837">PMC BUILDING</option>
<option value="838">PJICO BUILDING</option>
<option value="839">STAR BUILDING</option>
<option value="840">SAIGON LAND BUILDING</option>
<option value="841">TÍN NGHĨA BUILDING</option>
<option value="842">THIÊN HỒNG BUILDING</option>
<option value="843">TÀI LỘC OFFICE BUILDING</option>
<option value="844">BITEXCO NAM LONG BUILDING</option>
<option value="845">DC TOWER</option>
<option value="846">SAIGON SOFTWARE PARK</option>
<option value="847">TKT OFFICE BUILDING</option>
<option value="848">VIET DRAGON TOWER</option>
<option value="849">JABES 2 BUILDING</option>
<option value="850">MELODY TOWER</option>
<option value="851">IDC BUILDING</option>
<option value="852">THÁI SƠN BUILDING</option>
<option value="853">MAI HỒNG QUẾ BUILDING</option>
<option value="854">V&amp;D BUILDING</option>
<option value="856">CAO ỐC PAX SKY</option>
<option value="855">PASTEUR TOWER</option>
<option value="857">MB BANK TOWER</option>
<option value="858">ABACUS TOWER</option>
<option value="865">MOONLIGHT BOULEVARD</option>
<option value="869">TARA RESIDENCE</option>
<option value="870">VINCITY QUẬN 7</option>
<option value="871">GREEN RIVER QUẬN 8</option>
<option value="877">SAIGON SOUTH PLAZA</option>
<option value="879">THỦ THIÊM LAKEVIEW</option>
<option value="887">RIVER PANORAMA</option>
<option value="888">TÁI ĐỊNH CƯ BÌNH KHÁNH</option>
<option value="898">TINY HOUSE</option>
<option value="901">MASTERI AN PHÚ</option>
<option value="905">AURORA RIVERSIDE</option>
<option value="906">IMPERIAL PLACE</option>
<option value="914">LAVITA CHARM</option>
<option value="916">SÀI GÒN INTELA</option>
<option value="917">ADI LUCKY HOME</option>
<option value="918">THE PEGASUITE 2</option>
<option value="919">SERENITY SKY VILLAS</option>
<option value="923">CĂN HỘ HAUSNEO</option>
<option value="924">LAN PHƯƠNG - PRIMERLAND</option>
<option value="932">GRAND CENTRAL</option>
<option value="933">SUN VILLAGE APARTMENT</option>
<option value="934">BCONS TOWER</option>
<option value="935">ROSENA BÌNH THẠNH</option>
<option value="936">SUNWAH PEARL</option>
<option value="937">HIỆP THÀNH BUILDING</option>
<option value="938">CHUNG CƯ KHUÔNG VIỆT</option>
<option value="939">THỦ THIÊM GARDEN</option>
<option value="940">VINCITY QUẬN 9</option>
<option value="942">D1 MENSION</option>
<option value="944">OPAL SKYVIEW</option>
<option value="945">CARILLON 6</option>
<option value="946">SONATA RESIDENCES</option>
<option value="947">HIM LAM PHÚ AN</option>
<option value="948">VISION BÌNH TÂN</option>
<option value="950">SÀI GÒN WEST GARDEN</option>
<option value="951">CĂN HỘ HOÀNG QUỐC VIỆT</option>
<option value="952">SQUARE PLAZA</option>
<option value="953">PROSPER PLAZA</option>
<option value="958">ĐỨC LONG NEWLAND</option>
<option value="959">PALM HEIGHTS</option>
<option value="961">LANCASTER LINCOLN</option>
<option value="965">ASA LIGHT</option>
<option value="969">OPAL GARDEN</option>
<option value="970">SAFARI</option>
<option value="974">CITI SOHO</option>
<option value="979">SARIMI SALA</option>
<option value="980">CHƯƠNG DƯƠNG HOME</option>
<option value="986">NAM PHÚC - LE JARDIN</option>
<option value="987">DIAMOND LOTUS LAKE VIEW</option>
<option value="988">VALEO ĐẦM SEN</option>
<option value="989">RICHMOND CITY</option>
<option value="990">CENTANA THỦ THIÊM</option>
<option value="991">EXIM PEARL TOWER</option>
<option value="994">LA BONITA</option>
<option value="995">MADISON 15 THI SÁCH</option>
<option value="996">I-HOME XA LỘ HÀ NỘI</option>
<option value="1018">SCENIC VALLEY 2</option>
<option value="1019">C3 PARCSPRING</option>
<option value="1022">AMAZING CITY</option>
<option value="1025">9 VIEW APARTMENT</option>
<option value="1026">GIA PHÁT APARTMENT</option>
<option value="1027">SÀI GÒN MIA</option>
<option value="1028">M-ONE NAM SÀI GÒN</option>
<option value="1031">CARILLON 5</option>
<option value="1032">LUXURY HOME</option>
<option value="1033">DE CAPELLA</option>
<option value="1034">PARK VISTA</option>
<option value="1035">ASCOTT WATERFRONT SAIGON</option>
<option value="1037">DREAM HOME PALACE</option>
<option value="1039">TECCO CENTRAL HOME</option>
<option value="1041">NHÀ Ở CÁN BỘ QUÂN KHU 7</option>
<option value="1042">CHUNG CƯ NGUYỄN HUY LƯỢNG</option>
<option value="1048">LAVITA GARDEN</option>
<option value="1050">HQC 35 HỒ HỌC LÃM</option>
<option value="1051">CĂN HỘ RIVA PARK</option>
<option value="1052">SAIGON MIA</option>
<option value="1053">CHARMINGTON LA POINTE</option>
<option value="1054">MOONLIGHT PARK VIEW</option>
<option value="1057">CARA RIVERVIEW</option>
<option value="1059">SAMLAND AIRPORT</option>
<option value="1060">THE NASSIM THẢO ĐIỀN</option>
<option value="1063">PHÚ AN CENTER</option>
<option value="1064">CĂN HỘ SUNRIVER</option>
<option value="1065">AN GIA SKYLINE</option>
<option value="1070">HƯNG PHÁT SILVER STAR</option>
<option value="1076">CĂN HỘ LUXCITY</option>
<option value="1079">TÂN BÌNH APARTMENT</option>
<option value="1082">XI GRAND COURT</option>
<option value="1086">CARILLON 3</option>
<option value="1087">SAIGON PLAZA TOWER</option>
<option value="1088">THE ART</option>
<option value="1096">KHU CĂN HỘ IDICO TÂN PHÚ</option>
<option value="1097">SUNRISE CITY VIEW</option>
<option value="1098">GATEWAY THẢO ĐIỀN</option>
<option value="1099">GREEN HOME RESIDENCE</option>
<option value="1100">OPAL RIVERSIDE</option>
<option value="1101">CHUNG CƯ TDH - PHƯỚC LONG</option>
<option value="1103">CĂN HỘ FLORITA ĐỨC KHẢI</option>
<option value="1104">HQC HÓC MÔN</option>
<option value="1105">KINGSTON RESIDENCE</option>
<option value="1106">GOLDEN MANSION</option>
<option value="1107">VRG RIVER VIEW</option>
<option value="1108">GOLDLAND PLAZA</option>
<option value="1109">SOUTHERN DRAGON</option>
<option value="1112">DEPOT METRO THAM LƯƠNG</option>
<option value="1114">SAIGONRES PLAZA</option>
<option value="1115">CHUNG CƯ BỘ CÔNG AN</option>
<option value="1116">THE EVERRICH INFINITY</option>
<option value="1117">DREAM HOME RESIDENCE</option>
<option value="1118">FLORA ANH ĐÀO</option>
<option value="1119">WILTON TOWER</option>
<option value="1125">SKYWAY RESIDENCE</option>
<option value="1129">GRAND RIVERSIDE</option>
<option value="1130">CHUNG CƯ 312 LẠC LONG QUÂN</option>
<option value="1131">CHÁNH HƯNG APARTMENT</option>
<option value="1132">THE BOTANICA</option>
<option value="1133">FORTUNE APARTMENT</option>
<option value="1135">PERIDOT BUILDING</option>
<option value="1137">SKY CENTER</option>
<option value="1138">THE EASTER CITY</option>
<option value="1139">CHƯƠNG DƯƠNG GOLDEN LAND</option>
<option value="1140">MELODY RESIDENCES</option>
<option value="1145">GOLF VIEW TOWER</option>
<option value="1146">SOHO RIVERVIEW</option>
<option value="1147">ORCHARD GARDEN</option>
<option value="1148">CHUNG CƯ TUỆ TĨNH</option>
<option value="1149">SKY 9</option>
<option value="1150">FULL HOUSE</option>
<option value="1153">CHUNG CƯ 41BIS ĐIỆN BIÊN PHỦ</option>
<option value="1154">CHUNG CƯ THANH NIÊN</option>
<option value="1155">CĂN HỘ VĨNH TƯỜNG</option>
<option value="1156">GARDEN GATE</option>
<option value="1158">CITI HOME</option>
<option value="1160">SÀI GÒN APARTMENT</option>
<option value="1162">CĂN HỘ 51 CHÁNH HƯNG</option>
<option value="1164">SÀI GÒN METRO PARK</option>
<option value="1166">CHUNG CƯ PHẠM VIẾT CHÁNH</option>
<option value="1170">CHUNG CƯ ĐÔNG HƯNG</option>
<option value="1171">CHUNG CƯ 26 NGUYỄN THƯỢNG HIỀN</option>
<option value="1181">CHUNG CƯ MỸ THUẬN</option>
<option value="1180">CHUNG CƯ 10A TRẦN NHẬT DUẬT</option>
<option value="1179">MỸ CẢNH</option>
<option value="1177">CAO ỐC PHÚ NHUẬN</option>
<option value="1183">COMPASS LIVING PARK VIEW</option>
<option value="1184">CĂN HỘ PHÚ MỸ AN</option>
<option value="1185">CHUNG CƯ TRẦN VĂN KIỂU</option>
<option value="1186">CHUNG CƯ A.VIEW</option>
<option value="1187">RIVER GATE</option>
<option value="1190">DOCKLANDS SÀI GÒN</option>
<option value="1191">VILLA RIVIERA</option>
<option value="1197">CHUNG CƯ CÂY MAI</option>
<option value="1198">CHUNG CƯ AN THỊNH</option>
<option value="1199">CHUNG CƯ 12 VIEW</option>
<option value="1200">LUCKY PALACE</option>
<option value="1204">NGUYỄN QUYỀN PLAZA</option>
<option value="1205">CREC BUILDING TRƯƠNG ĐỊNH</option>
<option value="1210">THE HOLLYWOOD TOWER</option>
<option value="1211">CHUNG CƯ 155 NGUYỄN CHÍ THANH</option>
<option value="1212">CHUNG CƯ Z751 HÀ ĐÔ</option>
<option value="1215">CĂN HỘ 8X PLUS TRƯỜNG CHINH</option>
<option value="1219">KHU CĂN HỘ SACOMREAL-584</option>
<option value="1221">CARILLON 2</option>
<option value="1225">CHUNG CƯ TDH – PHƯỚC BÌNH</option>
<option value="1228">LONG PHỤNG RESIDENCE</option>
<option value="1229">GARDEN PLAZA 2</option>
<option value="1232">CĂN HỘ NHẤT LAN 3</option>
<option value="1233">BLUE STAR</option>
<option value="1234">THỦ THIÊM SKY</option>
<option value="1237">AN LỘC - AN PHÚC</option>
<option value="1238">CHUNG CƯ AN CƯ</option>
<option value="1243">MỸ GIANG</option>
<option value="1244">MỸ KHÁNH 3</option>
<option value="1245">MỸ KHÁNH 1</option>
<option value="1246">MỸ KHÁNH 2</option>
<option value="1248">CĂN HỘ 8X RAINBOW</option>
<option value="1249">KHU NHÀ PHỐ HƯNG PHƯỚC</option>
<option value="1250">CĂN HỘ AN VIÊN</option>
<option value="1251">CĂN HỘ 8X THÁI AN</option>
<option value="1253">MỸ VIÊN</option>
<option value="1254">CHUNG CƯ SAO MAI</option>
<option value="1256">SAMLAND GIAI VIỆT</option>
<option value="1257">THE MANSION</option>
<option value="1258">NGỌC KHÁNH TOWER</option>
<option value="1259">GREEN VIEW</option>
<option value="1260">SAIGONLAND APARTMENT</option>
<option value="1261">TANIBUILDING SƠN KỲ 2</option>
<option value="1262">CẢNH VIÊN 2</option>
<option value="1264">CẢNH VIÊN 1</option>
<option value="1266">CHUNG CƯ CỬU LONG</option>
<option value="1267">GARDEN COURT 2</option>
<option value="1268">MỸ KHANG</option>
<option value="1269">NAM KHANG</option>
<option value="1270">HƯNG VƯỢNG 3</option>
<option value="1271">HƯNG VƯỢNG 2</option>
<option value="1272">HƯNG VƯỢNG 1</option>
<option value="1273">MỸ PHÁT</option>
<option value="1274">CHUNG CƯ LÝ CHIÊU HOÀNG</option>
<option value="1275">MỸ PHƯỚC</option>
<option value="1278">MỸ PHÚC</option>
<option value="1280">LOTUS APARTMENT</option>
<option value="1281">KHU CĂN HỘ KHẢI HOÀN</option>
<option value="1286">CHUNG CƯ MỸ KIM</option>
<option value="1287">CHUNG CƯ ĐỒNG DIỀU</option>
<option value="1289">CHUNG CƯ TÂN MỸ</option>
<option value="1291">THE CBD PREMIUM HOME</option>
<option value="1293">CHUNG CƯ 203 NGUYỄN TRÃI</option>
<option value="1297">KHU CĂN HỘ AN HÒA</option>
<option value="1298">DETESCO LƯƠNG ĐỊNH CỦA</option>
<option value="1300">CHUNG CƯ PHÚ THỌ</option>
<option value="1301">CHUNG CƯ HOÀNG KIM</option>
<option value="1302">CĂN HỘ KHANG GIA</option>
<option value="1304">CHUNG CƯ NGUYỄN NGỌC PHƯƠNG</option>
<option value="1305">BIGEMCO BUILDING</option>
<option value="1306">CHUNG CƯ AN SƯƠNG</option>
<option value="1308">TANIBUILDING SƠN KỲ 1</option>
<option value="1311">GREENVIEW GARDEN</option>
<option value="1315">GREEN VALLEY</option>
<option value="1317">MỸ KHÁNH 4</option>
<option value="1318">KHU TÁI ĐỊNH CƯ PHÚ MỸ 2</option>
<option value="1320">GALAXY 9</option>
<option value="1322">HƯNG NGÂN GARDEN</option>
<option value="1324">LONG PHỤNG APARTMENT</option>
<option value="1327">THÁI SƠN APARTMENT</option>
<option value="1328">TOPAZ GARDEN</option>
<option value="1330">NAM AN APARTMENT</option>
<option value="1331">CĂN HỘ LINH TÂY</option>
<option value="1332">CHUNG CƯ MINH THÀNH</option>
<option value="1333">CHUNG CƯ MIẾU NỔI</option>
<option value="1335">USILK APARTMENT</option>
<option value="1336">CHUNG CƯ BÔNG SAO</option>
<option value="1338">CAO ỐC BÌNH MINH</option>
<option value="1340">TÂN PHƯỚC PLAZA</option>
<option value="1344">CĂN HỘ 8X ĐẦM SEN</option>
<option value="1346">SKY GARDEN II</option>
<option value="1347">SKY GARDEN I</option>
<option value="1348">C.T PLAZA NGUYÊN HỒNG</option>
<option value="1350">EHOME 2</option>
<option value="1352">EHOME 5 - THE BRIDGEVIEW</option>
<option value="1353">HQC PLAZA</option>
<option value="1354">CĂN HỘ BÌNH KHÁNH</option>
<option value="1355">CAO ỐC THỊNH VƯỢNG</option>
<option value="1356">GARDEN PLAZA 1</option>
<option value="1358">CHUNG CƯ TÔN THẤT THUYẾT</option>
<option value="1359">CHUNG CƯ KHÁNH HỘI 1</option>
<option value="1360">TECCO GREEN NEST</option>
<option value="1361">CHUNG CƯ HÀ KIỀU</option>
<option value="1362">CHUNG CƯ AN LỘC</option>
<option value="1363">LÊ THÀNH TÂN TẠO</option>
<option value="1364">HIM LAM CHỢ LỚN</option>
<option value="1365">CHUNG CƯ MỸ ĐỨC</option>
<option value="1366">I-HOME 1</option>
<option value="1367">TRUNG ĐÔNG PLAZA</option>
<option value="1368">BÀU CÁT II</option>
<option value="1371">CHUNG CƯ THẾ KỶ 21</option>
<option value="1373">CỘNG HÒA PLAZA</option>
<option value="1377">SAIGON MANSION</option>
<option value="1378">HOMYLAND 2</option>
<option value="1380">SUNVIEW TOWN</option>
<option value="1382">CHUNG CƯ MỸ AN - 3G</option>
<option value="1386">CHUNG CƯ MAN THIỆN</option>
<option value="1387">TÂN HƯƠNG TOWER</option>
<option value="1388">THE SPLENDOR</option>
<option value="1392">FIRST HOME THẠNH LỘC</option>
<option value="1393">DB COURT</option>
<option value="1394">HOA SEN - LOTUS APARTMENT</option>
<option value="1395">DREAM HOME</option>
<option value="1398">SGC NGUYỄN CỬU VÂN</option>
<option value="1405">GOOD HOUSE APARTMENT</option>
<option value="1406">CĂN HỘ HƯNG PHÁT</option>
<option value="1407">HAPPY VALLEY</option>
<option value="1412">CHEERY 4 COMPLEX</option>
<option value="1414">THE PRINCE RESIDENCE</option>
<option value="1418">SCREC II TOWER</option>
<option value="1420">SUNVIEW 3</option>
<option value="1421">PETROLAND TOWER</option>
<option value="1425">DEPOT METRO TOWER</option>
<option value="1427">LÊ THÀNH TWIN TOWERS</option>
<option value="1428">CHEERY 3 APARTMENT</option>
<option value="1429">GREEN PARK RESIDENCES</option>
<option value="1430">PARCSPRING</option>
<option value="1431">GRAND VIEW</option>
<option value="1435">HÀ ĐÔ GREEN VIEW</option>
<option value="1436">THỦ THIÊM XANH</option>
<option value="1437">KHU CĂN HỘ EHOME 3</option>
<option value="1438">CHEERY 2 APARTMENT</option>
<option value="1440">KHU CĂN HỘ TÂN MAI</option>
<option value="1444">HOMYLAND</option>
<option value="1446">THE EASTERN</option>
<option value="1447">BẢY HIỀN TOWER</option>
<option value="1449">THE ERA LẠC LONG QUÂN</option>
<option value="1450">BEE HOME</option>
<option value="1451">CHUNG CƯ B1 TRƯỜNG SA</option>
<option value="1454">AN GIA GARDEN</option>
<option value="1457">CAO ỐC RCL - BÌNH ĐÔNG</option>
<option value="1459">RCL TẠ QUANG BỬU</option>
<option value="1462">LEXINGTON RESIDENCE</option>
<option value="1471">CHUNG CƯ PETROLAND QUẬN 2</option>
<option value="1472">RIVER VALLEY</option>
<option value="1473">THE PANORAMA</option>
<option value="1474">RIVERSIDE RESIDENCE</option>
<option value="1476">THE HYCO4 TOWER</option>
<option value="1479">SKY SYMPHONY</option>
<option value="1480">KHU CĂN HỘ RES III</option>
<option value="1483">TDH - PHÚC THỊNH ĐỨC</option>
<option value="1484">NEW PEARL RESIDENCE</option>
<option value="1485">CHUNG CƯ KHÁNH HỘI 3</option>
<option value="1486">THÁI AN APARTMENT</option>
<option value="1487">KIM TÂM HẢI APARTMENT</option>
<option value="1488">CAO ỐC CINCO</option>
<option value="1489">GREEN BUILDING</option>
<option value="1492">SAILING TOWER</option>
<option value="1494">CHUNG CƯ GIA PHÚ HƯNG</option>
<option value="1495">THE HYCO4 TOWER</option>
<option value="1496">LÉMAN LUXURY APARTMENTS</option>
<option value="1497">MOON GARDEN</option>
<option value="1498">CHUNG CƯ AN BÌNH</option>
<option value="1499">KHU CĂN HỘ NBB GARDEN III</option>
<option value="1503">SACOMREAL HÙNG VƯƠNG</option>
<option value="1505">DRAGON HILL RESIDENCE AND SUITES 2</option>
<option value="1507">SUNNY THỦ THIÊM</option>
<option value="1509">HAPPY CITY - KHU ĐÔ THỊ HẠNH PHÚC</option>
<option value="1510">HOÀNG KIM THẾ GIA (THE GOLDEN DYNASTY)</option>
<option value="1514">TRIỀU AN TOWER</option>
<option value="1516">THIÊN LỘC TOWER</option>
<option value="1519">CITIZEN TRUNG SƠN</option>
<option value="1521">AN PHÚ PLAZA</option>
<option value="1527">SOUTHERN PALACE</option>
<option value="1528">KHU CĂN HỘ SHERWOOD RESIDENCE</option>
<option value="1529">KHU CĂN HỘ GIA TUỆ CENTRAL SQUARE</option>
<option value="1530">KHU CAO ỐC HỒNG TÂN</option>
<option value="1531">CHUNG CƯ BẮC BÌNH</option>
<option value="1532">LORI PLAZA</option>
<option value="1533">THE MARK</option>
<option value="1534">RUBY GARDEN</option>
<option value="1535">AN PHÚ APARTMENT</option>
<option value="1536">CHUNG CƯ TÂN THỊNH LỢI</option>
<option value="1537">CAO ỐC BMC HƯNG LONG</option>
<option value="1539">CHUNG CƯ CAO CẤP TAM BÌNH</option>
<option value="1541">XI RIVERVIEW PALACE</option>
<option value="1543">CĂN HỘ CAO CẤP MỸ LONG</option>
<option value="1544">CHUNG CƯ THỌ NAM SANG</option>
<option value="1545">CĂN HỘ QUANG THÁI</option>
<option value="1546">SAIGON PAVILLON</option>
<option value="1548">CHUNG CƯ CONIC ĐÌNH KHIÊM</option>
<option value="1549">CONIC GARDEN</option>
<option value="1550">CĂN HỘ MAY APARTMENTS</option>
<option value="1551">CHUNG CƯ PNT COURT</option>
<option value="1552">CĂN HỘ DA SÀ</option>
<option value="1553">CHUNG CƯ AN HÒA</option>
<option value="1559">VERONICA APARTMENTS</option>
<option value="1560">CHUNG CƯ NGUYỄN VĂN CỪ</option>
<option value="1561">VERONICA APARTMENTS</option>
<option value="1562">RIVERA PARK SÀI GÒN</option>
<option value="1563">CĂN HỘ INCOMEX</option>
<option value="1564">CỤM CHUNG CƯ ẤN QUANG</option>
<option value="1569">KHU DÂN CƯ BẮC LƯƠNG BÈO</option>
<option value="1571">CAO ỐC SÔNG ĐÀ TOWER</option>
<option value="1572">CHUNG CƯ 107 TRƯƠNG ĐỊNH</option>
<option value="1573">KHU CĂN HỘ BÌNH PHÚ</option>
<option value="1578">CHUNG CƯ NGUYỄN KIM</option>
<option value="1582">KHU NHÀ Ở GÒ SAO</option>
<option value="1584">CHUNG CƯ THIÊN QUÝ</option>
<option value="1585">CHUNG CƯ HÙNG VIỆT</option>
<option value="1586">CHUNG CƯ ĐIỀN PHÚC THÀNH</option>
<option value="1587">TÒA NHÀ HORIZON</option>
<option value="1588">CHUNG CƯ TÔ HIẾN THÀNH</option>
<option value="1592">MỸ PHÚ APARTMENT</option>
<option value="1593">TOPAZ CITY</option>
<option value="1599">NGỌC LAN APARTMENT</option>
<option value="1603">KHANG GIA TÂN HƯƠNG (LUCKY APARTMENT)</option>
<option value="1606">PETROVIETNAM GREEN HOUSE</option>
<option value="1609">BLUE DIAMOND TOWER</option>
<option value="1610">ÂU CƠ TOWER</option>
<option value="1612">CAO ỐC AN KHANG</option>
<option value="1614">TÒA NHÀ GREEN BUILDING</option>
<option value="1616">ĐẠI AN - SAIGON RIVERSIDE</option>
<option value="1618">H3 HOÀNG DIỆU</option>
<option value="1619">SKY GARDEN 3</option>
<option value="1620">RIVERPARK RESIDENCE</option>
<option value="1621">CẢNH VIÊN 3</option>
<option value="1622">CHUNG CƯ CAO TẦNG HIỆP TÂN</option>
<option value="1623">CAO ỐC ĐẠI THÀNH</option>
<option value="1624">T.N.T BUILDING</option>
<option value="1625">PHÚ GIA HƯNG APARTMENT</option>
<option value="1626">CARINA PLAZA</option>
<option value="1627">LOTUS GARDEN</option>
<option value="1631">CHUNG CƯ 283 LÊ QUANG ĐỊNH</option>
<option value="1633">HOÀNG ANH GOLD HOUSE</option>
<option value="1635">ANH TUẤN APARTMENT</option>
<option value="1636">THE HARMONA</option>
<option value="1637">HIM LAM RIVERSIDE</option>
<option value="1638">CĂN HỘ KHANG GIA GÒ VẤP</option>
<option value="1639">CHUNG CƯ LÊ THÀNH</option>
<option value="1640">BLUE SAPPHIRE BÌNH PHÚ</option>
<option value="1641">NAM MINH LONG</option>
<option value="1642">ĐẠT GIA RESIDENCE</option>
<option value="1643">LỮ GIA PLAZA</option>
<option value="1644">THIÊN NAM APARTMENT</option>
<option value="1645">NEWTOWN APARTMENT</option>
<option value="1646">CHUNG CƯ THANH NHỰT</option>
<option value="1647">TÂN TẠO PLAZA</option>
<option value="1648">CĂN HỘ NHẤT LAN</option>
<option value="1649">KHU CĂN HỘ MỸ ĐỨC</option>
<option value="1650">VALENTINA COURT</option>
<option value="1651">WATERFRONT RESIDENCES</option>
<option value="1652">CAO ỐC TDH - BÌNH CHIỂU</option>
<option value="1653">CAO ỐC PHỐ ĐÔNG - HOA SEN</option>
<option value="1654">BELLEZA APARTMENT</option>
<option value="1655">CHUNG CƯ THẾ HỆ MỚI</option>
<option value="1656">LAN PHƯƠNG MHBR TOWER</option>
<option value="1657">GREEN PARK BÌNH TÂN</option>
<option value="1658">CĂN HỘ CAO CẤP HOÀNG THÁP PLAZA</option>
<option value="1669">HIỆP THÀNH CITY</option>
<option value="1670">STOWN THỦ ĐỨC</option>
<option value="1671">VIN OFFICE</option>
<option value="1672">KINGDOM 101</option>
<option value="1679">RES 11</option>
<option value="1680">CITI ESTO</option>
<option value="1681">ONE VERANDAH MAPLETREE</option>
<option value="1682">THỦ THIÊM DRAGON</option>
<option value="1683">CALLA GARDEN</option>
<option value="1685">COSMO CITY</option>
<option value="1686">MASTERI M-ONE GÒ VẤP</option>
<option value="1687">SAIGONHOMES</option>
<option value="1688">GREEN FIELD</option>
