<option value="0">Chọn Dự án</option>
<option value="430">ELYSIA COMPLEX CITY</option>
<option value="502">HÒA BÌNH GREEN ĐÀ NẴNG</option>
<option value="503">CENTRAL COAST ĐÀ NẴNG</option>
<option value="504">VINPEARL CONDOTEL ĐÀ NẴNG</option>
<option value="556">ASIA PARK RESIDENCE</option>
<option value="726">LAKESIDE PALACE</option>
<option value="678">VINPEARL PREMIUM ĐÀ NẴNG</option>
<option value="718">KHU ĐÔ THỊ AN PHƯỚC</option>
<option value="727">CHĂM RIVER PARK</option>
<option value="729">HALLA JADE RESIDENCES</option>
<option value="733">PHOENIX COMPLEX ĐÀ NẴNG</option>
<option value="756">DRAGON VĨNH TRUNG</option>
<option value="765">VĨNH TRUNG PLAZA</option>
<option value="893">HIYORI GARDEN TOWER</option>
<option value="960">SUN PREMIER CONDOTEL ĐÀ NẴNG</option>
<option value="968">THE OCEAN SUITES</option>
<option value="983">FURAMA CONDOTEL ĐÀ NẴNG</option>
<option value="984">CĂN HỘ QUANG NGUYỄN</option>
<option value="1036">MƯỜNG THANH SƠN TRÀ</option>
<option value="1068">KHU QUÂN NHÂN 309</option>
<option value="1292">KHU CĂN HỘ F.HOME</option>
<option value="1309">HOÀNG ANH GIA LAI LAKE VIEW RESIDENCE</option>
<option value="1379">KHU NHÀ Ở XÃ HỘI BLUE HOUSE</option>
<option value="1424">NEST HOME</option>
<option value="1464">CĂN HỘ CAO CẤP AZURA</option>
<option value="1467">LA PAZ TOWER</option>
<option value="1481">BLOOMING TOWER ĐÀ NẴNG</option>
<option value="1511">OLALANI RIVERSIDE TOWERS</option>
<option value="1512">THE SUMMIT</option>
<option value="1570">CHUNG CƯ NGUYỄN ĐÌNH CHIỂU</option>
