<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API access token' => '',
    'Email' => '',
    'Expire At' => 'Hết hạn lúc',
    'Not Active' => '',
    'Password' => 'Mật khẩu',
    'Roles' => 'Vai trò',
    'Token' => '',
    'Use commas to separate tags' => 'Sử dụng dấu phẩy để ngăn cách các thẻ',

    '"{attribute}" must be a valid JSON' => '"{attribute}" phải đúng định dạng JSON',

    'Active' => 'Kíck hoạt',
    'Article ID' => 'ID Bài viết',
    'Article View' => 'Xem bài viết',
    'Author' => 'Tác giả',
    'Base URL' => 'Base URL',
    'Base Url' => 'Base Url',
    'Body' => 'Nội dung',
    'Back' => 'Quay lại',
    'Caption' => 'Tiêu đề',
    'Carousel ID' => 'ID Carousel',
    'Category' => 'Danh mục',
    'Comment' => 'Bình luận',
    'Component' => 'Thành phần',
    'Config' => 'Cấu hình',
    'Created At' => 'Đã tạo lúc',
    'Created at' => 'Đã tạo lúc',
    'Deleted' => 'Đã xóa',

    'Down to maintenance.' => 'Chuyển sang chế độ bảo trì.',

    'Delete' => 'Xóa',
    'E-mail' => 'E-mail',
    'File Type' => 'Loại file',
    'Firstname' => 'Tên chính',
    'Gender' => 'Nam',
    'ID' => 'ID',
    'Image' => 'Ảnh',
    'Key' => 'Khóa',
    'Last login' => 'Lần đăng nhập cuối',
    'Lastname' => 'Tên họ',
    'Locale' => 'Vùng',
    'Middlename' => 'Tên đệm',
    'Name' => 'Tên',
    'Order' => 'Thứ tự',
    'Page View' => 'Xem trang',
    'Parent Category' => 'Danh mục cha',
    'Path' => 'Đường dẫn',
    'Picture' => 'Ảnh',
    'Published' => 'Đã xuất bản',
    'Published At' => 'Xuất bản lúc',
    'Size' => 'Kích cớ',
    'Slug' => 'Bí danh',
    'Status' => 'Trạng thái',
    'Thumbnail Image' => 'Ảnh thumbnail',
    'Title' => 'Tiêu đề',
    'Type' => 'Loại',
    'Updated At' => 'Cập nhật lúc',
    'Updated at' => 'Cập nhật lúc',
    'Updater' => 'Người cập nhật',
    'Upload Ip' => 'IP',
    'Url' => 'Url',
    'User ID' => 'Mã thành viên',
    'Username' => 'Tên đăng nhập',
    'Value' => 'Giá trị',
    'Sub Category' => 'Danh mục con',
    'Excerpt' => 'Mô tả ngắn',
    'Price' => 'Giá SP',
    'Condition' => 'Thỏa thuận',
    'Price Text' => 'Nhập giá',
    'Public From' => 'Từ ngày',
    'Public To' => 'Đến ngày',
    'Attachments' => 'Đính kèm',
    'City' => 'Tỉnh/Thành Phố',
    'District' => 'Quận/Huyện',
    'Ward' => 'Làng/Xã',
    'Location' => 'Địa điểm',
    'Joined' => 'Đã tham gia',
    'Agencies' => 'Sàn giao dịch',

    'Incorrect Otp code.' => 'Sai mã xác nhận.',
    'Contact Seller' => 'Liên hệ với người bán',
    'Send a message' => 'Gửi thông tin liên hệ',
    'Seller information' => 'Thông tin người bán',

    'Add New' => 'Thêm mới',
    'Thumbnail' => 'Ảnh',
    'Sort Order' => 'Sắp xếp',

    'Are you sure to delete?' => 'Xác nhận xóa?',

    'excerpt' => 'Mô tả ngắn',
    'You are not allowed to perform this operation' => 'Bạn không được phép thực hiện chức năng này!',
    'Article Not Found' => 'Không tìm thấy bài viết',
    'Article Not Publishing' => 'Bài viết chưa được xuất bản',

    'View more' => 'Xem thêm',
    'Project' => 'Dự án',
    'Event' => 'Sự kiện',
    'News' => 'Tin tức',
    'Post Ads' => 'Tạo mới',
    'Update Ads' => 'Cập nhật',
    'Terms' => 'Điều khoản thông tin',
    'Property' => 'Bất động sản',
    'Remember above contact information' => 'Remember above contact information',

    'Select Payment Method' => 'Chọn phương thức thanh toán',
    'Make your Ad Premium' => 'Đặt tin quảng cáo',
    'Address' => 'Địa chỉ',
];
